In [10]:
import sys

sys.path.append('../../../')

from computer_vision.slowfast.mmengine.utils.dl_utils.misc import has_batch_norm

In [11]:
a={}
type(a)

dict

In [3]:
import torch

base_param_settings={'params':torch.tensor([0.], dtype=torch.float)}
print(f"{base_param_settings=}")
model = torch.nn.Linear(10, 10)
optim = torch.optim.SGD(model.parameters(), lr=3e-4)
print(f"{optim.defaults=}")
base_param_settings.update(**optim.defaults)
print(f"{base_param_settings=}")

base_param_settings={'params': tensor([0.])}
optim.defaults={'lr': 0.0003, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False}
base_param_settings={'params': tensor([0.]), 'lr': 0.0003, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False}


In [20]:
params=[]
for param_group in optim.param_groups:
    params.extend(param_group['params'])
print(type(param_group['params']), len(param_group['params']))#, param_group['params']
print(len(params))
params_=list(filter(lambda p: p.requires_grad and p.grad is not None, params))
len(params_)

<class 'list'> 2
2


0

In [8]:
optim.param_groups[0]['lr']=0.01
print(f"{optim.param_groups=}")
print(f"{base_param_settings=}")

optim.param_groups=[{'params': [Parameter containing:
tensor([[-0.0794,  0.0770,  0.1008, -0.0490, -0.1850, -0.1845, -0.2837,  0.0894,
          0.1536, -0.1437],
        [-0.2524,  0.1056, -0.1133,  0.0830,  0.0026, -0.2804, -0.2086,  0.0194,
         -0.2770, -0.0723],
        [ 0.2400, -0.1919, -0.2402,  0.0671, -0.0763,  0.2641, -0.0410,  0.0911,
         -0.2236,  0.1986],
        [-0.0412,  0.1793, -0.2481, -0.2092, -0.2052,  0.0252, -0.0951,  0.2809,
          0.2635,  0.3022],
        [-0.1822, -0.1458, -0.1798, -0.0363, -0.2942,  0.1085, -0.2617,  0.1484,
          0.0029, -0.0433],
        [-0.0113,  0.1598,  0.1121, -0.0826,  0.2345, -0.2559, -0.0431,  0.0629,
          0.1817,  0.1916],
        [ 0.2175, -0.1053,  0.1765, -0.0205,  0.2825,  0.2349, -0.1610, -0.2268,
          0.0748,  0.0517],
        [ 0.2935,  0.0831, -0.0548, -0.1202,  0.0823, -0.1518, -0.1411,  0.0564,
         -0.1033,  0.0444],
        [-0.0966,  0.0656,  0.2225, -0.0574, -0.1879,  0.1692, -0.0303,  0

In [2]:
from typing import Any, List, Union
import torch
import numpy as np

BoolTypeTensor = Union[torch.BoolTensor, torch.cuda.BoolTensor]
LongTypeTensor = Union[torch.LongTensor, torch.cuda.LongTensor]
IndexType: Union[Any] = Union[str, slice, int, list, LongTypeTensor,
                              BoolTypeTensor, np.ndarray]
IndexType.__args__

(str,
 slice,
 int,
 list,
 torch.LongTensor,
 torch.cuda.LongTensor,
 torch.BoolTensor,
 torch.cuda.BoolTensor,
 numpy.ndarray)

In [ ]:
NotImplementedError

In [7]:
import sys

sys.path.append('../../../')

from computer_vision.slowfast.mmengine.structures.base_data_element import BaseDataElement
from computer_vision.slowfast.mmengine.structures.instance_data import InstanceData

In [35]:
import torch
import torch.nn.functional as F

tensor_list=[torch.rand(3,10,4,4), torch.rand(3,10,6,4), torch.rand(3,7,4,3), torch.rand(3,6,1,4)]
all_sizes=torch.Tensor([i.shape for i in tensor_list])
all_sizes

tensor([[ 3., 10.,  4.,  4.],
        [ 3., 10.,  6.,  4.],
        [ 3.,  7.,  4.,  3.],
        [ 3.,  6.,  1.,  4.]])

In [36]:
max_sizes=torch.max(all_sizes, dim=0)[0]
print(f'{max_sizes=}')
padded_sizes=max_sizes-all_sizes
padded_sizes # C, T, H, W

max_sizes=tensor([ 3., 10.,  6.,  4.])


tensor([[0., 0., 2., 0.],
        [0., 0., 0., 0.],
        [0., 3., 2., 1.],
        [0., 4., 5., 0.]])

In [37]:
dim=x[0].ndim
pad=torch.zeros(len(padded_sizes), 2*dim, dtype=torch.int)
pad[:,1::2]=padded_sizes[:,range(dim-1,-1,-1)]
pad

tensor([[0, 0, 0, 2, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 2, 0, 3, 0, 0],
        [0, 0, 0, 5, 0, 4, 0, 0]], dtype=torch.int32)

In [38]:
batch_tensor=[]
for idx, tensor in enumerate(tensor_list):
    batch_tensor.append(
        F.pad(tensor, tuple(pad[idx].tolist()), value=0)
    )
    print(idx, batch_tensor[-1].shape)

0 torch.Size([3, 10, 6, 4])
1 torch.Size([3, 10, 6, 4])
2 torch.Size([3, 10, 6, 4])
3 torch.Size([3, 10, 6, 4])
