In [3]:
import numpy as np

In [9]:
a=np.vstack([i*np.ones((1,7)) for i in range(10)])
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9.]])

In [10]:
np.roll(a, -6,axis=0)

array([[6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5.]])

In [12]:
np.arange(10)[:1]

array([0])